# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-10 16:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='我的故事', verbose_name='内容')),
            ],
            options={
                'verbose_name': '关于我',
                'verbose_name_plural': '关于我',
            },
        ),
        migrations.CreateModel(
            name='LearnProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='标题')),
                ('content', models.TextField(help_text='板块内容', verbose_name='内容')),
                ('pub', models.DateField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('image', models.ImageField(upload_to='learn/%Y/%m', verbose_name='学习图片')),
            ],
            options={
                'verbose_name': '学无止境',
                'verbose_name_plural': '学无止境',
                'ordering': ['-pub'],
            },
        ),
        migrations.CreateModel(
            name='LifeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='标题')),
                ('content', models.TextField(help_text='板块内容', verbose_name='内容')),
                ('pub', models.DateField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('image', models.ImageField(upload_to='life/%Y/%m', verbose_name='生活图片')),
            ],
            options={
                'verbose_name': '故事与酒',
                'verbose_name_plural': '故事与酒',
                'ordering': ['-pub'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='标题')),
                ('content', models.TextField(help_text='博客内容', verbose_name='内容')),
                ('pub', models.DateField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('image', models.ImageField(upload_to='first/%Y/%m', verbose_name='首页图片')),
            ],
            options={
                'verbose_name': '博客首页',
                'verbose_name_plural': '博客首页',
                'ordering': ['-pub'],
            },
        ),
    ]
